### PR TITLE
Add compiled binary, add installation instructions, move source code to /src

### PR DESCRIPTION
**Pull request by ghost**
I made these changes to make it easier to support users to manually install the addon, see here: https://github.com/xHN35RQ/enjoyreading-ng/releases/latest

thanks

### CODE REVIEW

**Comment by rbrito** [comment]
Hi.

You closed this pull request before I could take a look a it... Are you going to send another pull request?

If so, it would be nice if you could separate the changes that are logically independent into separate commits. You can use `git rebase` for that.

BTW, thanks for the contribution. I am waiting for your answer so that I know what to do.

**Comment by ghost** [comment]
I'll re-open in just a second. I reverted the main changes and added the built XPI on a release instead of in the repository itself. And I'll do the git rebase :+1: thanks!

**Comment by rbrito** [comment]
Hi, Nic.

On Apr 11 2015, Nic wrote:

> I'll re-open in just a second. I reverted the main changes and added the
> built XPI on a release instead of in the repository itself. And I'll do
> the git rebase :+1: thanks!

Oh, that's sweet! Having the changes being granular and independent will be
super nice!

Thanks,

## 

Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by ghost** [comment]
I am learning my way through git so thanks for telling me about the git rebase, I actually didn't need to use it this time, since I only edited the Readme so it's a single commit as you'll see on #3 - but I'll definitely use rebase in future.

**Pull request closed without merging**
